# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('keyword', models.CharField(max_length=30)),
                ('abstract', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='Insert time')),
            ],
        ),
    ]
